dash/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import serve
from django.conf.urls.static import static



urlpatterns = [
    path('', views.dashboard_view, name='dashboard'),
    path('/joblistings', views.job_dashboard_view, name='dashboard'),
    path('/all', views.index, name='dashboard'),
    path('/edit_job/<int:job_id>/', views.edit_job, name='edit_job'),
    path('/search', views.search_jobs, name='search_jobs'),
    path('/jobs/<int:job_id>/', views.job_detail, name='job_detail'),
    path('/submissions/', views.submissions, name='submissions'),
    path('/myapplications/', views.my_files, name='my_files'),
    path('/submissions/<int:submission_id>/download/', views.download_submission, name='download_submission'),
    path('/send_message/<int:submission_id>/', views.send_message, name='send_message'),
    path('/inbox', views.inbox, name='inbox'),
    path('/reply_message/<int:message_id>/', views.reply_message, name='reply_message'),
    path('/user_messages/<str:username>/', views.user_messages, name='user_messages'),
    #path('resumes/<path:path>', views.protected_serve, {'document_root': settings.STATICFILES_DIRS}),
    #path('/resumes/<int:pk>/download/', views.login_required(views.download_resume), name='download_resume'),

    # other URL patterns go here
]

hehe/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('dashboard', include('dash.urls')),
    path('', include('front.urls')),

]
#if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dash/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth import get_user_model

class JobPost(models.Model):

    JOB_TYPE_CHOICES = (
        ('full_time', 'Full Time'),
        ('part_time', 'Part Time'),
        ('contract', 'Contract'),
        ('internship', 'Internship'),
        ('freelance', 'Freelance'),
    )


    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    description = models.TextField()
    job_type = models.CharField(max_length=20, choices=JOB_TYPE_CHOICES, default='full_time')
    created_at = models.DateTimeField(auto_now_add=True)



class Submission(models.Model):
    job_post = models.ForeignKey(JobPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    resume = models.FileField(upload_to='resumes/')
    created_at = models.DateTimeField(auto_now_add=True)


class Message(models.Model):
    subject = models.CharField(max_length=255)
    body = models.TextField()
    sender = models.ForeignKey(get_user_model(), related_name='sent_messages', on_delete=models.CASCADE)
    recipient = models.ForeignKey(get_user_model(), related_name='received_messages', on_delete=models.CASCADE)
    parent_message = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    sent_at = models.DateTimeField(auto_now_add=True)
    unread = models.BooleanField(default=True)
    read_at = models.DateTimeField(null=True, blank=True)
    is_read = models.BooleanField(default=False)


    class Meta:
        ordering = ('-sent_at',)



    def __str__(self):
        return self.title

dash/forms.py
from django import forms
from .models import JobPost
from django import forms
from .models import Submission
from .models import Message
from django.contrib.auth.models import User


JOB_TYPE_CHOICES = (
        ('full_time', 'Full Time'),
        ('part_time', 'Part Time'),
        ('contract', 'Contract'),
        ('internship', 'Internship'),
        ('freelance', 'Freelance'),
    )



class JobPostForm(forms.ModelForm):
    job_type = forms.ChoiceField(choices=JOB_TYPE_CHOICES)
    class Meta:
        model = JobPost
        fields = ['title','company', 'job_type','description']


class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ('resume',)

class MessageForm(forms.ModelForm):
    recipient = forms.CharField()

    class Meta:
        model = Message
        fields = ('recipient', 'subject', 'body')
    
    def __init__(self, *args, **kwargs):
        recipient_username = kwargs.pop('recipient_username', None)
        super().__init__(*args, **kwargs)
        if recipient_username:
            try:
                recipient = User.objects.get(username=recipient_username)
                self.initial['recipient'] = recipient.id
            except User.DoesNotExist:
                pass
    
    

    def clean_recipient(self):
        recipient = self.cleaned_data['recipient']
        try:
            recipient = User.objects.get(username=recipient)
        except User.DoesNotExist:
            raise forms.ValidationError("Recipient does not exist")
        return recipient

    def save(self, sender):
        message = super().save(commit=False)
        message.sender = sender
        message.recipient = self.cleaned_data['recipient']
        message.save()
        return message

dash/views.py
from django import forms
from django.http import FileResponse, Http404, HttpResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.template import engines
from .forms import JobPostForm, SubmissionForm
from .models import JobPost, Submission
from django.utils import timezone
from django.db.models import Q
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Message
from .models import Submission
from .forms import MessageForm
from itertools import groupby
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test
from django.views.static import serve
from django.shortcuts import render
from django.db.models import Q
from django.template import engines
from django.template import Context





@login_required
def reply_message(request, message_id):
    message = get_object_or_404(Message, pk=message_id, recipient=request.user)
    initial_data = {
        'subject': f"Re: {message.subject}",
        'recipient': message.sender,
    }
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(sender=request.user)
            message.sender = request.user
            message.save()
            messages.success(request, 'Your reply has been sent.')
            print(message_id)
            print(request.user)

            return redirect('/dashboard/inbox')

    else:
        form = MessageForm(initial=initial_data)
    print(message_id)
    print(request.user)

    return render(request, 'communication/send_message.html', {'form': form})




@login_required
def inbox(request):
    messages = Message.objects.filter(Q(recipient=request.user) | Q(sender=request.user))
    usernames = set()
    unique_messages = []
    for message in messages:
        if message.sender.username not in usernames:
            usernames.add(message.sender.username)
            unique_messages.append({'sender__username': message.sender.username})
    unread_count = Message.objects.filter(recipient=request.user, unread=True).count()
    return render(request, 'communication/inbox.html', {'messages': unique_messages, 'unread_count': unread_count})



@login_required
def user_messages(request, username):
    received_messages = Message.objects.filter(sender__username=username, recipient=request.user)
    sent_messages = Message.objects.filter(sender=request.user, recipient__username=username)
    messages = (received_messages | sent_messages).order_by('-sent_at')
    for message in messages:
        if message.recipient == request.user and not message.read_at:
            message.read_at = timezone.now()
            message.save()
    unread_count = Message.objects.filter(recipient=request.user, read_at=None).count()
    return render(request, 'communication/user_messages.html', {'messages': messages, 'username': username, 'unread_count': unread_count})








@login_required
def submissions(request):
    user = request.user
    submissions = Submission.objects.filter(job_post__user=user)
    success_message = messages.get_messages(request)
    return render(request, 'submissions.html', {'submissions': submissions, 'success_message': success_message})


@login_required
def send_message(request, submission_id, message_id=None):
    submission = get_object_or_404(Submission, pk=submission_id, job_post__user=request.user)
    parent_message = get_object_or_404(Message, pk=message_id, recipient=request.user) if message_id else None

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(sender=request.user)
            message.sender = request.user
            message.recipient = User.objects.get(username=submission.user.username)  # set the recipient to the submission user
            message.parent_message = parent_message
            message.save()
            messages.success(request, 'Your message has been sent.')
            return redirect('submissions')
    else:
        initial_data = {'parent_message': parent_message} if parent_message else {'recipient': submission.user.username}
        form = MessageForm(initial=initial_data)

    form.fields['recipient'].widget = forms.HiddenInput()
    return render(request, 'communication/send_message.html', {'form': form, 'submission': submission, 'parent_message': parent_message, 'recipient': submission.user.username})




@login_required
def dashboard_view(request):
    username = request.user.username
    job_posts = JobPost.objects.filter(user=request.user)
    message_count = Message.objects.filter(recipient=request.user, unread=False).count()
    if request.method == 'POST':
        if 'post_job' in request.POST:
            form = JobPostForm(request.POST)
            if form.is_valid():
                job_post = form.save(commit=False)
                job_post.user = request.user
                job_post.save()
                return redirect('dashboard')
        elif 'delete_job' in request.POST:
            job_id = request.POST.get('delete_job')
            job_post = JobPost.objects.get(id=job_id, user=request.user)
            job_post.delete()
            return redirect('dashboard')
    else:
        form = JobPostForm()
    return render(request, 'auth/mdashboard.html', {'username': username, 'form': form, 'job_posts': job_posts, 'message_count': message_count})



@login_required
def job_dashboard_view(request):
    username = request.user.username
    job_posts = JobPost.objects.filter(user=request.user).order_by('-created_at')
    submission_count = Submission.objects.filter(job_post__user=request.user).count()
    
    if request.method == 'POST':
        if 'post_job' in request.POST:
            form = JobPostForm(request.POST)
            if form.is_valid():
                job_post = form.save(commit=False)
                job_post.user = request.user
                job_post.save()
                return redirect('dashboard')
        elif 'delete_job' in request.POST:
            job_id = request.POST.get('delete_job')
            job_post = JobPost.objects.get(id=job_id, user=request.user)
            job_post.delete()
            return redirect('dashboard')
    else:
        form = JobPostForm()
    
    return render(request, 'auth/joblistings.html', {'username': username, 'form': form, 'job_posts': job_posts, 'submission_count': submission_count})










def index(request):
    if request.method == 'POST' and 'delete_job' in request.POST:
        job_id = request.POST.get('delete_job')
        try:
            job_post = JobPost.objects.get(id=job_id)
            job_post.delete()
            messages.success(request, 'Job post deleted successfully.')
        except JobPost.DoesNotExist:
            messages.error(request, 'Job post not found.')
    
    job_posts = JobPost.objects.order_by('-created_at')
    paginator = Paginator(job_posts, 5) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'auth/index.html', {'page_obj': page_obj})




@login_required
def edit_job(request, job_id):
    job_post = get_object_or_404(JobPost, id=job_id)

    if request.method == 'POST':
        form = JobPostForm(request.POST, request.FILES, instance=job_post)
        if form.is_valid():
            job_post = form.save(commit=False)
            job_post.created_at = timezone.now()  # Set created_at time to current time
            job_post.save()
            return redirect('/dashboard/all')
        else:
            print(form.errors)
    else:
        form = JobPostForm(instance=job_post)

    return render(request, 'edit_job.html', {'form': form})


def search_jobs(request):
    django_engine = engines['django']
    query = request.GET.get('q')
    if query:
        # Search for job posts that contain the query string in their title, description or company name.
        job_posts = JobPost.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query) | Q(company__icontains=query)
        ).order_by('-created_at')
    else:
        job_posts = JobPost.objects.all().order_by('-created_at')

    if job_posts.exists():
        return render(request, 'search_jobs.html', {'job_posts': job_posts})
    else:
        error_message = django_engine.from_string('Sorry, we can\'t find this:' + query)
        print(error_message)
        h=error_message.render({}, request)
        #template = django_engine.get_template('search_jobs.html')
       # context = {'error_message': error_message}
        return render(request, 'search_jobs.html' ,{'error_message': h})
        


#def job_detail(request, job_id):
 #   job_post = get_object_or_404(JobPost, id=job_id)
 #   return render(request, 'job_details.html', {'job_post': job_post})

@login_required
def job_detail(request, job_id):
    job_post = get_object_or_404(JobPost, pk=job_id)
    if request.method == 'POST':
        form = SubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            submission = form.save(commit=False)
            submission.job_post = job_post
            submission.user = request.user
            submission.save()
            messages.success(request, 'Your resume has been submitted successfully.')
            return redirect('/dashboard/myapplications', pk=job_id)
    else:
        form = SubmissionForm()
    return render(request, 'sub.html', {'job_post': job_post, 'form': form})

"""
@login_required
def submissions(request):
    user = request.user
    submissions = Submission.objects.filter(job_post__user=user)
    return render(request, 'submissions.html', {'submissions': submissions})
"""

#@login_required
#def my_files(request):

dash/templates/base.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900">
    {% include 'partials/nav.html' %}
    <div class="container mx-auto px-10">
      {% block content %}
      {% endblock content %}
      {% include 'partials/footer.html' %}
    </div>
  
</body>
</html>

dash/templates/edit_job.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-lg my-2 leading-7 text-gray-500 dark:text-gray-400">Edit job post</h1>
  <form class="text-lg my-2 leading-7 text-gray-500 dark:text-gray-400" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mt-4">
      <label for="id_title" class="block text-gray-700 font-bold mb-2">Title</label>
      <input type="text" name="title" id="id_title" value="{{ form.title.value }}" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
    </div>
    <div class="mt-4">
      <label for="id_company" class="block text-gray-700 font-bold mb-2">Company</label>
      <input type="text" name="company" id="id_company" value="{{ form.company.value }}" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
    </div>
    <div class="mt-4">
      <label for="id_description" class="block text-gray-700 font-bold mb-2">Description</label>
      <textarea name="description" id="id_description" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ form.description.value }}</textarea>
    </div>
    <div class="mt-4">
      <label for="id_job_type" class="block text-gray-700 font-bold mb-2">Job Type</label>
      <select name="job_type" id="id_job_type" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        <option value="full_time" {% if form.job_type.value == "full_time" %}selected{% endif %}>Full Time</option>
        <option value="part_time" {% if form.job_type.value == "part_time" %}selected{% endif %}>Part Time</option>
        <option value="contract" {% if form.job_type.value == "contract" %}selected{% endif %}>Contract</option>
        <option value="internship" {% if form.job_type.value == "internship" %}selected{% endif %}>Internship</option>
        <option value="freelance" {% if form.job_type.value == "freelance" %}selected{% endif %}>Freelance</option>
      </select>
    </div>
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-4 rounded focus:outline-none focus:shadow-outline" type="submit">
      Save changes
    </button>
  </form>
{% endblock %}

dash/templates/job_details.html
{% extends 'base.html' %}

{% block content %}
<div class="dark:bg-slate-800 job-post max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
    <div class="md:flex">
      <div class="md:shrink-0">
      </div>
      <div class="p-8">
        <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">{{ job_post.title }}</div>
        <p class="text-xs my-2 leading-7 text-gray-500 dark:text-gray-400">{{ job_post.company }}</p>
        <p id="job-description" class="mt-2 text-slate-500">{{ job_post.description|truncatewords:50 }}</p>
        {% if job_post.description|wordcount > 50 %}
        <button id="show-full-description-button" class="text-sm text-gray-500 hover:text-gray-700 focus:outline-none focus:text-gray-700" onclick="showFullDescription()">Show Full Description</button>
        {% endif %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="job_post_id" value="{{ job_post.id }}">
            <div class="mt-4">
                <label for="resume">Upload your resume:</label>
                <input type="file" id="resume" name="resume">
            </div>
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">Submit Resume</button>
        </form>
      </div>
    </div>
</div>
{% endblock content %}

dash/templates/my.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<link href="https://cdn.jsdelivr.net/npm/daisyui@2.50.1/dist/full.css" rel="stylesheet" type="text/css" />
<script src="https://cdn.tailwindcss.com"></script>

<link href="https://cdn.jsdelivr.net/npm/daisyui@2.50.1/dist/full.css" rel="stylesheet" type="text/css" />
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2/dist/tailwind.min.css" rel="stylesheet" type="text/css" />

  <style>
    h1, h2, h3, h4, h5, h6 {
      color: #9b5de5;
    }
    .delete-button {
      background-color: #e63946;
      color: white;
    }
    .delete-button:hover {
      background-color: #ff5252;
    }
  </style>
{% endblock %}

{% block content %}
  <h1 class="text-purple-600 text-3xl font-bold mb-4">My Applications</h1>

  {% if submissions %}
    <table class="text-blue-600 table table-hover w-full">
      <thead>
        <tr>
          <th class="tracking-tighter text-gray-500 md:text-lg dark:text-gray-400 px-4 py-2">Job Title</th>
          <th class="tracking-tighter text-gray-500 md:text-lg dark:text-gray-400 px-4 py-2">Company</th>
          <th class="tracking-tighter text-gray-500 md:text-lg dark:text-gray-400 px-4 py-2">Resume</th>
          <th class="tracking-tighter text-gray-500 md:text-lg dark:text-gray-400 px-4 py-2">Submitted</th>
          <th class="tracking-tighter text-gray-500 md:text-lg dark:text-gray-400 px-4 py-2">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for submission in submissions %}
          <tr class="border-b border-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800">
            <td class="px-4 py-2">{{ submission.job_post.title }}</td>
            <td class="px-4 py-2">{{ submission.job_post.company }}</td>
            <td class="px-4 py-2">
              <a href="{{ submission.resume.url }}" class="text-blue-600 hover:text-blue-800">{{ submission.resume.name|slice:"8:" }}</a>
            </td>
            <td class="px-4 py-2">{{ submission.created_at }}</td>
            <td class="px-4 py-2">
              <form method="POST" action="{% url 'my_files' %}">
                {% csrf_token %}
                <input type="hidden" name="submission_id" value="{{ submission.id }}">
                <button type="button" class="text-red-600 btn btn-outline btn-square delete-button" onclick="deleteSubmission(this.form)">
                  <span class="inline-block animate-pulse">Delete</span>
                </button>
              </form>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="5" class="px-4 py-2">No files found.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>You haven't uploaded any files yet.</p>
  {% endif %}

  <script>
    function deleteSubmission(form) {
      if (confirm('Are you sure you want to delete this file?')) {
        form.submit();
      }
    }
  </script>
{% endblock %}

dash/templates/search_jobs.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-lg my-2 leading-7 text-gray-500 dark:text-gray-400">Job Search</h1>

  <!-- tailwind -->
  <form method="GET" action="{% url 'search_jobs' %}">
    <label class="relative block">
      <span class="sr-only">Search</span>
      <span class="absolute inset-y-0 left-0 flex items-center pl-2">
        <svg class="h-5 w-5 fill-slate-300" viewBox="0 0 20 20"><!-- ... --></svg>
      </span>
      <input type="text" id="query" name="q" value="{{ request.GET.q }}" class="placeholder:italic placeholder:text-slate-400 block bg-white w-full border border-slate-300 rounded-md py-2 pl-9 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm" placeholder="Search for anything..." type="text" name="search"/>
      <br><button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" type="submit">Search</button>
    </label>
  </form>

  <hr>

  <h2 class="text-lg my-2 leading-7 text-gray-500 dark:text-gray-400">Results:</h2>

  {% if job_posts %}
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      {% for job_post in job_posts %}
        <div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
          <a href="#">
            <h3 class="mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">{{ job_post.title }}</h3>
          </a>
          <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Company: {{ job_post.company }}</p>
          <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Posted on: {{ job_post.created_at }}</p>
          <a href="{% url 'job_detail' job_id=job_post.pk %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            Read more
            <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </a>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <p class="text-lg my-2 leading-7 text-gray-500 dark:text-gray-400">{{ error_message }} No jobs found.</p>
    {% endif %}
  {% endblock %}

dash/templates/sub.html
{% extends 'base.html' %}

{% block content %}



<h1 class="max-w-lg text-3xl font-semibold leading-relaxed text-gray-900 dark:text-white transform  transition-all ">{{ job_post.title }}</h1>

<p class="text-xl font-semibold text-blue-600/100 dark:text-blue-500/100 transform hover:scale-105 transition-all duration-500 cursor-pointer inline-block bg-gray-900 px-2 py-1 rounded-lg shadow-md hover:shadow-lg"> {{ job_post.company }} </p>

<p class="text-gray-500 whitespace-pre-line dark:text-gray-400">{{ job_post.description }}</p>


<!-- for job poster -->
<div class="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6 mb-4">
  {% if request.user == job_post.user %}
    {% if job_post.submission_set.exists %}
      <h2 class="text-2xl font-bold text-purple-600 mb-4">Submissions:</h2>
      <ul class="list-disc pl-6 mb-4">
      {% for submission in job_post.submission_set.all %}
        <li class="text-lg text-gray-900 dark:text-white mb-2 hover:text-purple-600 transition duration-300 ease-in-out">
          <span class="font-bold">{{ submission.user.username }}</span> - 
          <a href="{{ submission.resume.url }}" class="text-purple-600 hover:text-purple-400 transition duration-300 ease-in-out">Download resume</a>
        </li>
      {% endfor %}
      </ul>
    {% else %}
      <p class="text-lg text-purple-600 mb-4">No submissions yet.</p>
    {% endif %}
  {% else %}
    <h2 class="text-2xl font-bold text-purple-600 mb-4">Submissions:</h2>
    <p class="text-lg text-gray-900 dark:text-white mb-4">You must be the job poster to view submissions.</p>
 
</div>




<!-- hehe resume submit-->
<div class="bg-gray-800 rounded-md shadow-lg p-4 hover:shadow-2xl transition-shadow duration-300">
  <h2 class="text-lg font-medium text-white mb-4">Submit your resume:</h2>
  <form method="post" enctype="multipart/form-data" class="space-y-4">
    {% csrf_token %}
    <div class="flex flex-col space-y-2">
      <label for="{{ form.title.id_for_label }}" class="text-white font-medium">{{ form.title.label }}</label>
      {{ form.title }}
    </div>
    <div class="flex flex-col space-y-2">
      <label for="{{ form.company.id_for_label }}" class="text-white font-medium">{{ form.company.label }}</label>
      {{ form.company }}
    </div>
    <div class="flex flex-col space-y-2">
      <label for="{{ form.description.id_for_label }}" class="text-white font-medium">{{ form.description.label }}</label>
      {{ form.description }}
    </div>
    <div class="flex flex-col items-center justify-center space-y-2">
      <label for="file-upload" class="relative cursor-pointer text-white font-bold py-2 px-4 rounded-full bg-gradient-to-r from-purple-500 to-indigo-600 transition-colors duration-300 ease-in-out hover:from-purple-600 hover:to-indigo-700 animate-fade-in">
        <span>Choose file</span>
        <input id="file-upload" name="resume" type="file" class="sr-only">
      </label>
      <p id="file-name" class="text-xs text-gray-500">No file chosen</p>
      <p class="text-xs text-gray-500">PDF of Max size 50 MB.</p>
    </div>
    <div class="flex justify-end">
    <button type="submit" class="bg-purple-500 hover:bg-purple-600 text-white font-bold py-2 px-4 rounded-full transition-colors duration-300 ease-in-out hover:shadow-md animate-fade-in">Submit</button>
    </div>
  </form>
</div>

    

    <script>
      const fileInput = document.getElementById('file-upload');
      const fileName = document.getElementById('file-name');
    
      fileInput.addEventListener('change', () => {
        fileName.textContent = fileInput.files[0].name;
      });
    </script>


  
</div>

  
{% endif %}
{% endblock %}